### ISSUE TITLE
Exception: Signature length must be 128 but it is 97.

### ISSUE THREAD

**Issue by SemElVik** [habanoz/tezos-reward-distributor#60] opened 2019-03-08 19:29 UTC
Describe the bug

 ```2019-03-08 21:09:08,222 - main - ERROR - consumer0 - Error at reward payment
Traceback (most recent call last):
  File "/home/t32/tezos-reward-distributor/src/pay/payment_consumer.py", line 72, in run
    payment_logs = batch_payer.pay(payment_items, self.verbose, dry_run=self.dry_run)
  File "/home/t32/tezos-reward-distributor/src/pay/batch_payer.py", line 96, in pay
    payments_log = self.pay_single_batch_wrap(payment_items_chunk, verbose=verbose, dry_run=dry_run)
  File "/home/t32/tezos-reward-distributor/src/pay/batch_payer.py", line 111, in pay_single_batch_wrap
    return_code, operation_hash = self.pay_single_batch(payment_items, verbose, dry_run=dry_run)
  File "/home/t32/tezos-reward-distributor/src/pay/batch_payer.py", line 228, in pay_single_batch
    "Signature length must be 128 but it is {}. Signature is '{}'".format(len(signed_bytes), signed_bytes))
Exception: Signature length must be 128 but it is 97. Signature is 'edsigty6YKZVDf-------------------UDQBhT2yYWgcSRss```

**Expected behavior**
reward payment

**Environment**
 - Source Code
 - Chain mainnet
 -python3 src/main.py

**Additional context**
this happens about the fifth time.
I have to close the window (tab) of the console and open a new tab. and start the new.  then it works.

**Comment by habanoz** [comment] 2019-03-09 05:05
I experienced a similar issue. 
> Signature length must be 128 but it is 95. Signature is 'sigW1Co7daGdWoN6rY.....

Trying to collect more information.

**Comment by habanoz** [comment] 2019-03-09 12:35
Made a small change. If the signature length is not as expected it will log the situation and try again. 
Not a real fix but should keep us going until the root cause is found.

**Comment by SemElVik** [comment] 2019-03-09 12:41
updated.

**Comment by utdrmac** [comment] 2019-03-20 16:13
https://github.com/habanoz/tezos-reward-distributor/commit/8a2ea605d4fc4d9d3fd87d10e84253d48706a63f

This is an issue. 
`2019-03-20 16:07:46,555 - main - WARNING - consumer0 - Signature length must be 128 but it is 95. Signature is 'sigmRwPVbXeC16EMLA7D1pp7Q22NnL5V45K164XQhpAytrf5ZPJ5MwHNiZXioaWmH5jgph1QWQr588HHB7j1wTgpafXxxXx'`

The following patch reverts the above commit and allows things to work as before:

```
$ git diff src/pay/batch_payer.py
diff --git a/src/pay/batch_payer.py b/src/pay/batch_payer.py
index 70bf900..1e89487 100644
--- a/src/pay/batch_payer.py
+++ b/src/pay/batch_payer.py
@@ -230,11 +230,11 @@ class BatchPayer():
         else:
             raise Exception("Signature '{}' is not in expected format".format(signed_bytes))

-        if len(decoded_signature) != 128:  # must be 64 bytes
-            # raise Exception("Signature length must be 128 but it is {}. Signature is '{}'".format(len(signed_bytes), signed_bytes))
-            logger.warn(
-                "Signature length must be 128 but it is {}. Signature is '{}'".format(len(signed_bytes), signed_bytes))
-            return False, ""
+        #if len(decoded_signature) != 128:  # must be 64 bytes
+        #    # raise Exception("Signature length must be 128 but it is {}. Signature is '{}'".format(len(signed_bytes), signed_bytes))
+        #    logger.warn(
+        #        "Signature length must be 128 but it is {}. Signature is '{}'".format(len(signed_bytes), signed_bytes))
+        #    return False, ""
```

**Comment by habanoz** [comment] 2019-03-20 17:27
@utdrmac Thanks for the patch. The patch, as I understand, removes length check. Do you think length check is unnecessary?

**Comment by utdrmac** [comment] 2019-03-20 17:57
Yes, it just removes the check. Have you verified this line is correct?

`decoded_sig_signature = decoded[6:][:-8]  # first 3 bytes sig, last 4 bytes checksum`

The [goTezos library](https://github.com/DefinitelyNotAGoat/go-tezos/blob/15b05ebd5b2b0e5e0f9349b078d0a6c72123a902/goTezosOpertations.go#L68) only strips off the first 10:
 `decodedSignature = decodedSignature[10:(len(decodedSignature))]`

**Comment by habanoz** [comment] 2019-03-20 20:21
> decoded_sig_signature = decoded[6:][:-8] # first 3 bytes sig, last 4 bytes checksum

This line is verified. tezos-signer produces generic signatures (sigXXXX). In that case first 6 bytes need to be removed. tezos-client produces edsig signatures (edsigXXXX) in which case first 10 bytes need to be removed.

**Comment by habanoz** [comment] 2019-03-20 20:27
I removed the length constraint as you suggested but I left the length check. If an operation fails for some reason I want to see the length of signed bytes from the log file to make sure it is not related to length.

**Comment by habanoz** [comment] 2019-04-06 19:36
Closing. No issues reported after removing length check.

**Comment by habanoz** [comment] 2019-04-10 19:41
Issue persists. Example log:

2019-04-10 15:42:39,713 - main - DEBUG - consumer0 - Running 5 operations
2019-04-10 15:42:40,167 - main - DEBUG - consumer0 - Forging 5 operations
2019-04-10 15:42:41,720 - main - DEBUG - consumer0 - Preapplying the operations
2019-04-10 15:42:42,129 - main - DEBUG - consumer0 - Injecting 5 operations
2019-04-10 15:42:42,130 - main - WARNING - consumer0 - Signature length must be 128 but it is 95. Signature is 'sigQ.......'
2019-04-10 15:42:42,548 - main - ERROR - consumer0 - Error in inject response 'Unexpected server answer

**Comment by SemElVik** [comment] 2019-04-11 16:20
for information:

I am using 2 versions.
latest (v.3), and version 2.
It seems on v.2 I had a problem recently.   `Exception: Signature '98' length must be 64`

I did not notice it on v.3, because there is an auto-repeat on error. maybe there is no error signature.

**Comment by habanoz** [comment] 2019-06-08 17:18
the root cause is found and fixed. No more signature related errors are expected.

**Closed by habanoz** 2019-06-08 17:18 UTC

**Comment by utdrmac** [comment] 2019-06-08 20:56
@habanoz Can you link the PR to this bug?

**Comment by habanoz** [comment] 2019-06-09 14:11
https://github.com/habanoz/tezos-reward-distributor/commit/55a8e90f0d71fe6ef0e12982fbdabe4c09c5074a

Please note that it is not in the master branch yet.
