### ISSUE TITLE
Compatibility to Baking Bad

### ISSUE THREAD

**Issue by amani1104** [habanoz/tezos-reward-distributor#52] opened 2019-02-22 09:40 UTC
**Is your feature request related to a problem? Please describe.**
[Baking Bad](https://baking-bad.org) is a service for delegators to compare rewards with actual received payments from the baker. For its calculations it uses 6 fractional digits for both owed rewards and percentage share of the total reward of the baker. Although both can be configured in tezos-reward-distributor (prcnt_scale : 6; pymnt_scale : 6), the actual received payments to delegators does not match with actual rewards, thus resulting in a message from Baking Bad that the payments are less or greater than expected. 

**Describe the solution you'd like**
I have re-calculated the rewards to delegators as displayed by Baking Bad and can confirm that these match the actual rewards owed by bakers. There thus seems to be an issue in the calculations made by the tezos-reward-distributor. Calculations should be improved so that these match actual rewards up to 6 fractional digits. 

<img width="405" alt="baking_bad" src="https://user-images.githubusercontent.com/40321348/53233125-e5309b00-368c-11e9-8643-44167fa406a9.png">

<img width="393" alt="payouts" src="https://user-images.githubusercontent.com/40321348/53234074-072b1d00-368f-11e9-84be-2c593c85893e.png">

**Comment by habanoz** [comment] 2019-02-22 11:54
Both values can be set to None to avoid any rounding. 
prcnt_scale : None
pymnt_scale : None

Would you please try with those settings, and please report any mismatches between your calculations and TRD output.

**Comment by amani1104** [comment] 2019-02-22 15:52
This is the output from Baking Bad without rounding: 

<img width="404" alt="payouts_no_rounding" src="https://user-images.githubusercontent.com/40321348/53253621-f647cf00-36c1-11e9-9af7-84246a34d39a.png">
There is still a small mismatch, unfortunately.

**Comment by SemElVik** [comment] 2019-02-22 17:06
No need to equal Baking bad. they are not a reference service.
compare on TzScan.
I have everything exactly calculated.
the same values ​​are set in the # None + commission (fee) is paid from the baker.

**Comment by habanoz** [comment] 2019-02-25 05:50
@amani1104 this may be because of miscalculations in Baking Bad service, or some other thing related to calculations e.g. excluded delegators, special ratios. Please note that I do not state baking bad calculations are not correct, but we cannot verify this.

TRD calculations are accurate because they are simple multiplication, division and summation operations which can easily be tracked by looking at the source code. 

We cannot put effort to provide compatibility to a third party service which is not widely used. Baking Bad service should prove its usefulness and accuracy first. 

If you point out any calculation errors at TRD output and provide enough data to reproduce it, we will fix it asap. We are also open to contributions through pull requests. 

Closing the issue, you may reopen it anytime.

**Closed by habanoz** 2019-02-25 05:50 UTC
